### ISSUE TITLE
Current `main` is unstable

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-icc-service#55]
When trying to build a container based on the current `main` branch, the following error appears:
```
docker-icc-1               | Error while building:
docker-icc-1               |  # github.com/OpenSlides/openslides-icc-service/internal/notify
docker-icc-1               | internal/notify/notify.go:36:11: topic.Topic is not a generic type
docker-icc-1               | internal/notify/notify.go:46:38: invalid operation: cannot index topic.WithClosed (value of type func(closed <-chan struct{}) topic.Option)
docker-icc-1               | internal/notify/notify.go:172:14: topic.Topic is not a generic type
docker-icc-1               | # github.com/OpenSlides/openslides-icc-service/internal/applause
docker-icc-1               | internal/applause/applause.go:37:13: topic.Topic is not a generic type
docker-icc-1               | internal/applause/applause.go:48:40: invalid operation: cannot index topic.WithClosed (value of type func(closed <-chan struct{}) topic.Option)
docker-icc-1               | 
```

**Comment by ostcar** [comment]
I can not reproduce this.  How exactly did you start the build process?

**Comment by GabrielInTheWorld** [comment]
```
make stop-dev
docker system prune --volumes
./services-to-main.sh -p
make run-dev
```

**Comment by ostcar** [comment]
I think this can be closed as well. See https://github.com/OpenSlides/openslides-autoupdate-service/issues/458 If not, please reopen.

From reading the error message that to pasted here and in the autoupdate service, I have an idea why the problem could have happened.

The docker-dev-images of my repos have fixed dependencies. When the code changes, the service is rebuild, but the dependencies can not change. So when the dependencies changes, you have to rebuild the image. If not, you get errors like this one.
