### ISSUE TITLE
Virtual applause doesn't work

### ISSUE THREAD

**Issue by MSoeb** [OpenSlides/openslides-icc-service#65]
The virtual applause function didn't work. Setting the check mark in Settings does nothing.

Reproduction:
1. Open a meeting
2. Go to Settings -> livestream
3. Add a livestream URL to activate livestream window
4. activate "Enable virtual applause -> save 
5. try the applause button on the leftside of the livestream window.

What should happen: Set the check box should activate virtual applause.

**Comment by ostcar** [comment]
@jsangmeister i will have a look at since next week.

**Comment by ostcar** [comment]
It worked for me. But the README was wrong. I fixed the README in #67 

You have to use the url `/system/icc/applause?meeting_id=1` to receive applause. Did you do this in your test?

**Comment by jsangmeister** [comment]
Yes, it works now, thank you. Seems like I tried to receive the applaus via the `notifiy` route.

I will take a look at why this does not work in the client.
